### ISSUE TITLE
ValueError: time data '10/18/2023, 12:07' does not match format '%m/%d/%Y, %H:%M:%S'

### ISSUE THREAD

**Issue by Saharel001** [openWB/core#1178]
Habe heute folgenden Fehler bekommen (aktuelles master)

`2023-10-18 12:07:50,865 - {helpermodules.timecheck:345} - {ERROR:MainThread} - Fehler im System-Modul
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/helpermodules/timecheck.py", line 341, in get_difference
    end = datetime.datetime.strptime(timestamp_end, "%m/%d/%Y, %H:%M:%S")
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '10/18/2023, 12:07' does not match format '%m/%d/%Y, %H:%M:%S'
2023-10-18 12:07:50,876 - {helpermodules.timecheck:320} - {ERROR:MainThread} - Fehler im System-Modul
Traceback (most recent call last):`

Das Ergebnis sind fehlende Zeiten in der Ladeübersicht
![image](https://github.com/openWB/core/assets/24453343/83bb03ed-b4c1-41c2-bef2-2b3e71681124)

**Comment by benderl** [comment]
Die Logmeldunbg ist leider aus dem Zusammenhang gerissen und zeigt nicht die Ursache des Fehlers.
