### ISSUE TITLE
Fehler im Rfid-Modul

### ISSUE THREAD

**Issue by Saharel001** [openWB/core#1179]
2023-10-18 12:33:57,982 - {modules.internal_chargepoint_handler.rfid:138} - {ERROR:Internal Chargepoint} - Fehler im Rfid-Modul
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/modules/internal_chargepoint_handler/rfid.py", line 124, in _read_events
    async for event in device.async_read_loop():
  File "/usr/lib/python3.9/asyncio/coroutines.py", line 127, in coro
    res = yield from res
  File "/home/openwb/.local/lib/python3.9/site-packages/evdev/eventio_async.py", line 98, in next_batch_ready
    future.set_result(next(self.current_batch))
  File "/home/openwb/.local/lib/python3.9/site-packages/evdev/eventio.py", line 71, in read
    events = _input.device_read_many(self.fd)
OSError: [Errno 19] No such device

Der RFID Reader ist keine openWB Hardware, hat bis jetzt aber immer funktioniert. USB RFID als HID.

**Comment by Saharel001** [comment]
Problem gefunden, sitzt vorm Gerät ;) Device ist abgestützt. Abziehen anstecken läuft.
