### ISSUE TITLE
Zeitladen: Phasenumschaltung wird nicht getriggert

### ISSUE THREAD

**Issue by MartinRinas** [openWB/core#2095]
Zeitladefenster aktiv, Ladevorgang startet mit der vorgegebenen Stromstärke, allerdings läuft timecheck in eine Fehler was vermutlich die Umschaltung von 1p auf 3p verhindert.

`2024-12-20 20:48:02,830 - {control.chargepoint.chargepoint:447} - {ERROR:MainThread} - Fehler in der Ladepunkt-Klasse von 27
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/control/chargepoint/chargepoint.py", line 441, in check_phase_switch_completed
    check_timestamp(self.data.control_parameter.timestamp_charge_start,
  File "/var/www/html/openWB/packages/helpermodules/timecheck.py", line 225, in check_timestamp
    if (create_timestamp() - duration) > timestamp:
TypeError: '>' not supported between instances of 'float' and 'NoneType'`

timestamp_charge_start ist nicht gesetzt:

`2024-12-20 20:48:02,861 - {control.data:268} - {INFO:MainThread} - cp26
ChargepointData(control_parameter=ControlParameter(chargemode=<Chargemode.PV_CHARGING: 'pv_charging'>, current_plan=None, failed_phase_switches=0, imported_at_plan_start=12414586.91, imported_instant_charging=None, limit=None, min_current=6, phases=1, prio=True, required_current=6, required_currents=[0.0, 6, 0.0], state=0, submode=<Chargemode.PV_CHARGING: 'pv_charging'>, timestamp_charge_start=None, timestamp_last_phase_switch=0, timestamp_switch_on_off=None), get=Get(charge_state=False, charging_current=0, charging_power=0, charging_voltage=0, connected_vehicle=ConnectedVehicle(config=ConnectedConfig(average_consumption=17, charge_template=0, chargemode='stop', current_plan=0, ev_template=0, priority=False, time_charging_in_use=False), info=ConnectedInfo(id=0, name='Ladepunkt'), soc=43.0), currents=[0.0, 0.0, 0.0], daily_imported=7876.0, daily_exported=0.0, error_timestamp=None, evse_current=0, e
[2024-12-20 204800,987.log](https://github.com/user-attachments/files/18214800/2024-12-20.204800.987.log)
xported=0, fault_str='Kein Fehler.', fault_state=0, imported=12414586.91, phases_in_use=1, plug_state=True, power=0, rfid_timestamp=None, rfid=None, serial_number=None, soc=None, soc_timestamp=None, state_str=None, vehicle_id=None, voltages=[225.63, 219.04, 225.57]), set=Set(charging_ev=17, charging_ev_prev=17, current=0, energy_to_charge=0, loadmanagement_available=True, log=Log(chargemode_log_entry='_', costs=0, imported_at_mode_switch=12414586.91, imported_at_plugtime=12414586.91, imported_since_mode_switch=0, imported_since_plugged=0.0, range_charged=0, time_charged='00:00', timestamp_start_charging=None, ev=-1, prio=False, rfid=None, serial_number=None, soc_at_start=None, soc_at_end=None, range_at_start=None, range_at_end=None), manual_lock=False, phases_to_use=1, plug_state_prev=True, plug_time=1734701282.275742, required_power=1380.0, rfid=None, current_prev=0, target_current=0, charging_ev_data=<control.ev.ev.Ev object at 0x6cf527d8>, ocpp_transaction_id=None), config=Config(configuration={'ip_address': '192.168.178.51', 'duo_num': 0}, ev=17, name='Garage', type='external_openwb', template=0, connected_phases=3, phase_1=2, auto_phase_switch_hw=True, control_pilot_interruption_hw=True, id=26, ocpp_chargebox_id=None))
`

bin auf dem aktuellen master https://github.com/openWB/core/commit/7799925e9622d2e9bb780bcd1537013946ff47a2

vollständiges Log: [2024-12-20 204800,987.log](https://github.com/user-attachments/files/18214803/2024-12-20.204800.987.log)

**Comment by MartinRinas** [comment]
die relevante Zeile wurde in diesem PR geändert: https://github.com/openWB/core/pull/1974

**Comment by LKuemmel** [comment]
Problem ist im verlinkten PR gelöst.
