### ISSUE TITLE
Fehler im Lastmanagement Modul 

### ISSUE THREAD

**Issue by DetMoerk** [openWB/core#265]
Ich bekomme einen Fehler im Lastmanagement Modul. Referenziert wird der Zähler 4 (mein VZLogger per JSON). Kann es sein, dass es hier auf Grund von fehlenden Einzelphasen eine Meldung gibt?

Ich versuch mal noch mehr raus zu finden.

```
2022-01-11 15:54:19,677 - {/packages/control/counter.py:370} - ERROR - Fehler in der Zähler-Klasse von 4
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/control/counter.py", line 367, in put_stats
    Pub().pub("openWB/set/counter/0/set/consumption_left", self.data["set"]["consumption_left"])
KeyError: 'consumption_left'
2022-01-11 15:54:29,653 - {/packages/control/loadmanagement.py:261} - ERROR - Fehler im Lastmanagement-Modul
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/control/loadmanagement.py", line 252, in _check_max_power
    consumption_left = data.data.counter_data[evu_counter].data[
KeyError: 'consumption_left'
2022-01-11 15:54:29,664 - {/packages/control/counter.py:370} - ERROR - Fehler in der Zähler-Klasse von 4
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/control/counter.py", line 367, in put_stats
    Pub().pub("openWB/set/counter/0/set/consumption_left", self.data["set"]["consumption_left"])
KeyError: 'consumption_left'

```

VG
Det

**Comment by DetMoerk** [comment]
in control/counter.py Zeile 367 sollte wohl nicht fix auf counter/0/ gesetzt werden oder? Oder ist counter/0 ein spezieller counter? 

```
    def put_stats(self):
        try:
            Pub().pub("openWB/set/counter/0/set/consumption_left", self.data["set"]["consumption_left"])

```

**Comment by LKuemmel** [comment]
Am Anfang war der Zähler 0 der EVU-Zähler. Mittlerweile wird der EVU-Zähler aus der Hierarchie ermittelt. Das war wohl noch ein Relikt.

**Comment by DetMoerk** [comment]
Yeah, jetzt kommen bei mir keine ERROR Meldungen mehr :-).
