### ISSUE TITLE
'ChargepointState' object has no attribute 

### ISSUE THREAD

**Issue by jbereuter** [openWB/core#581]
bei einem der letzten Updates hat sich ein Fehler eingeschlichen. Auf der Startseite erscheint der Fehler 
<class 'AttributeError'> 'ChargepointState' object has no attribute 'read_tag' 
beim Ladepunkt und das Logfile sagt: 

`
2022-10-16 13:42:40,844 - {soc.modules.common.fault_state:40} - ERROR - Ladepunkt: FaultState FaultStateLevel.ERROR, FaultStr <class 'AttributeError'> 'ChargepointState' object has no attribute 'read_tag', Traceback: 
Traceback (most recent call last):
  File "/var/www/html/openWB/packages/modules/common/store/_api.py", line 37, in update_values
    component.store.update()
  File "/var/www/html/openWB/packages/modules/common/store/_api.py", line 31, in update
    self.delegate.update()
  File "/var/www/html/openWB/packages/modules/common/store/_chargepoint.py", line 40, in update
    pub_to_broker("openWB/set/chargepoint/" + str(self.num) + "/get/read_tag", self.state.read_tag)
AttributeError: 'ChargepointState' object has no attribute 'read_tag'`

**Comment by LKuemmel** [comment]
Das Problem sollte mit PR #582 behoben sein. Bitte nochmal ein Update machen.
